AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket in Mumbai Region

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-mumbai-s3-bucket-unique123
      Tags:
        - Key: Environment
          Value: Dev

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref MyS3Bucket
